-- bier definition

CREATE TABLE bier (
  id	INT	NOT NULL    IDENTITY    PRIMARY KEY,
  naam varchar(40) DEFAULT NULL,
  brouwer varchar(40) DEFAULT NULL,
  type varchar(40) DEFAULT NULL,
  gisting varchar(40) DEFAULT NULL,
  perc float DEFAULT NULL,
  inkoop_prijs decimal(5,2) NOT NULL
);

INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Abondance mirabellen','Brouwerij de Troch','overige','spontane',0.035,4.39),
	 ('Abondance pÃªche','Brouwerij de Troch','overige','spontane',0.035,4.34),
	 ('Adler','Brouwerij Haacht','dortmunder','lage',0.0,3.53),
	 ('Aerts 1900','Brouwerij Palm','overige','hoge met nof',0.074,2.66),
	 ('Affligem christmas','Brouwerij de Smedt','overige','hoge',0.07,3.68),
	 ('Affligem donker','Brouwerij de Smedt','dubbel','hoge met nof',0.065,2.44),
	 ('Affligem helder','Brouwerij de Smedt','overige','hoge met nof',0.065,2.16),
	 ('Affligem rood','Brouwerij de Smedt','overige','hoge met nof',0.065,4.49),
	 ('Affligem tripel','Brouwerij de Smedt','tripel','hoge met nof',0.09,4.95),
	 ('Affligem van t patersvat','Brouwerij de Smedt','overige','hoge met nof',0.065,3.29);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Akila pils','Brouwerij Louwaege','pilsener','lage',0.05,2.59),
	 ('Alexander Rodenbach','Bierbrouwerij Rodenbach','overige','hoge+melkzure',0.062,4.08),
	 ('Alken export','Alken-Maes (zetel Alken)','pilsener','lage',0.045,4.62),
	 ('Allard extra','Brasserie Allard et Groetembril','saison','hoge met nof',0.07,2.86),
	 ('Allard extra vieille','Brasserie Allard et Groetembril','saison','hoge met nof',0.07,4.46),
	 ('Ambiorix dubbel','Brouwerij Slagmuylder','dubbel','hoge met nof',0.078,2.7),
	 ('Anglo pils','Alken-Maes (zetel Waarloos)','pilsener','lage',0.049,4.14),
	 ('Anglo pils','Alken-Maes (zetel Alken)','pilsener','lage',0.048,4.59),
	 ('Antiek','Brouwerij Isebaert','overige','hoge',0.08,2.52),
	 ('Antigoon','Brouwerij Isebaert','overige','hoge',0.08,2.83);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Arabier','De Dolle Brouwers','overige','?',0.0,4.6),
	 ('Aro pils','Brouwerij Haacht','pilsener','lage',0.05,3.49),
	 ('Artevelde','Brouwerij L. Huyghe N.V.','ale','hoge',0.067,4.67),
	 ('Artevelde grand cru','Brouwerij L. Huyghe N.V.','overige','hoge met nof',0.064,4.88),
	 ('Artevelde pils','Brouwerij L. Huyghe N.V.','pilsener','lage',0.051,2.39),
	 ('Artois export','Artois (groep Interbrew)','pilsener','lage',0.051,4.33),
	 ('Artvelde grand cru op gist','Brouwerij L. Huyghe N.V.','overige','hoge met nof',0.064,3.45),
	 ('Artvelde menta','Brouwerij L. Huyghe N.V.','overige','lage',0.054,2.29),
	 ('Artvelde op gist','Brouwerij L. Huyghe N.V.','ale','hoge',0.067,2.09),
	 ('Augustijn','Brouwerij Bios','overige','hoge met nof',0.08,4.56);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Augustijn grand cru','Brouwerij Bios','tripel','hoge met nof',0.09,2.53),
	 ('Avec les Bons Voeux de la brasserie Dupo','Brasserie Dupont','overige','hoge met nof',0.096,2.98),
	 ('Bacchus','Brouwerij Van Honsebrouck','Vlaamse bruine','hoge',0.048,2.33),
	 ('Baf','Brouwerij de Smedt','Belgische ale','hoge',0.05,3.69),
	 ('Bailus','Brasserie du Bocq','dubbel','hoge met nof',0.088,3.44),
	 ('Bakelandt','Brouwerij van Eecke','overige','hoge met nof',0.075,4.16),
	 ('Bass Old Barley Stout','Lamot (groep Interbrew)','stout','hoge',0.064,2.48),
	 ('Bass pale ale','Lamot (groep Interbrew)','pale ale','hoge',0.052,3.93),
	 ('Battin Edelpils','Brasserie Battin','pilsener','lage',0.0475,4.2),
	 ('Battin Gambrinus','Brasserie Battin','pilsener','lage',0.058,4.23);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Battin Gambrinus bock','Brasserie Battin','bokbier','lage',0.07,3.54),
	 ('Battin Gambrinus urtyp','Brasserie Battin','pilsener','lage',0.06,2.99),
	 ('Bavik super pils','Bavik - De Brabandere','pilsener','lage',0.049,2.34),
	 ('Belga pils','Brouwerij Leroy','pilsener','lage',0.05,3.72),
	 ('Belle Vue frambozen','Belle Vue','framboise','spontane',0.054,3.6),
	 ('Belle Vue gueuze lambic \"cuvÃ©e\"','Belle Vue','gueuze','spontane',0.051,4.83),
	 ('Belle Vue kriek lambic','Belle Vue','kriekenbier','spontane',0.052,2.37),
	 ('Belle Vue kriek lambic \"cuvÃ©e\"','Belle Vue','kriekenbier','spontane',0.052,4.33),
	 ('Benedict','Brouwerij De Kluis (groep Interbrew)','dubbel','hoge met nof',0.07,3.57),
	 ('Bergenbier','Artois (groep Interbrew)','pilsener','lage',0.051,2.84);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('n Seule','Brouwerij Slagmuylder','overige','hoge met nof',0.06,4.49),
	 ('t Paterke Achelse Kluis','Brouwerij R. Gielen','dubbel','hoge met nof',0.06,2.94),
	 ('203 Hamse witten','Brouwerij Vieille Villers','witbier','lage',0.053,2.23),
	 ('406 Wuitensbier','Brouwerij Vieille Villers','dubbel','hoge',0.062,3.32),
	 ('1664 de Kronenbourg','Alken-Maes (zetel Alken)','superpils','lage',0.055,4.93),
	 ('A la ferme','Brouwerij Isebaert','overige','hoge',0.08,3.7),
	 ('Abbaye dAulne ADA 6Â° sur lie','Brouwerij de Smedt','overige','hoge met nof',0.065,4.68),
	 ('Abbaye dAulne ADA 8Â° Selection','Brouwerij de Smedt','overige','hoge',0.08,4.33),
	 ('Abbaye dAulne ADA 10Â° superbe','Brouwerij de Smedt','gerstewijn','hoge',0.0,2.6),
	 ('Abbaye de Bonne EspÃ©rance','Brasserie LefÃ¨bvre','overige','hoge met nof',0.08,3.99);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Abbaye de Brogne Tripel sur lie','Brouwerij de Smedt','tripel','hoge met nof',0.09,4.17),
	 ('Abbaye de Cambron','Brasserie de Silly','saison','hoge',0.058,3.89),
	 ('Abbaye de Gembloux','Brasserie LefÃ¨bvre','overige','hoge met nof',0.08,4.92),
	 ('Abbaye de la Moinette','Brasserie Dupont','overige','hoge met nof',0.085,4.92),
	 ('Abbaye de Saint-Ghislain','Brasserie Dupont','overige','hoge met nof',0.085,4.87),
	 ('Abbaye des Rocs','Brasserie de lAbbaye des Rocs (Brasseri','overige','hoge met nof',0.09,4.57),
	 ('Abbaye du Val St.-Lambert','Brasserie Allard et Groetembril','overige','hoge+melkzure',0.095,3.24),
	 ('Abdij van Steenbrugge','Brouwerij De Gouden Boom','dubbel','hoge met nof',0.065,3.49),
	 ('Abdijbier Loo','Brouwerij Isebaert','tripel','hoge met nof',0.075,2.71),
	 ('Abondance banaan','Brouwerij de Troch','overige','spontane',0.035,4.11);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Abondance framboos','Brouwerij de Troch','framboise','spontane',0.035,4.43),
	 ('Abondance kriek','Brouwerij de Troch','overige','spontane',0.035,4.8),
	 ('Beyerd Speciaal','Brouwerij Sterkens','ale','hoge',0.065,2.72),
	 ('Beyerd speciaal 150','Brouwerij Sterkens','tripel','hoge',0.08,3.2),
	 ('Bezebier','Brouwerij Van Honsebrouck','overige','spontane',0.05,2.84),
	 ('BÃ©casse gueuze','Brabrux (Groep Belle-Vue)','gueuze','spontane',0.052,2.61),
	 ('Biermarkt super pils','Brouwerij Verhaeghe','pilsener','lage',0.04,2.5),
	 ('BiÃ¨re de la Commanderie de piÃ©ton','Brasserie Allard et Groetembril','overige','hoge+melkzure',0.095,2.71),
	 ('BiÃ¨re des Ducs Lothier','Brasserie LefÃ¨bvre','overige','hoge met nof',0.08,4.01),
	 ('BiÃ¨re des SorciÃ¨res dEllezelles','Brasserie Voisin','overige','hoge met nof',0.068,3.94);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('BiÃ¨re du Boucanier','Brouwerij Bios','gerstewijn','hoge met nof',0.11,2.68),
	 ('BiÃ¨re la Pax chatelet','Brasserie LefÃ¨bvre','overige','hoge met nof',0.08,2.57),
	 ('Bink','Huisbrouwerij Kerkom','overige','hoge met nof',0.055,2.8),
	 ('Bios export','Brouwerij Bios','pilsener','lage',0.05,4.3),
	 ('Bios Vlaamse bourgogne','Brouwerij Bios','Vlaamse bruine','hoge met nof',0.06,2.11),
	 ('Blanch-ke','Brouwerij Van Honsebrouck','witbier','hoge met nof',0.05,4.64),
	 ('Block export','Brouwerij de Block','pilsener','lage',0.046,2.87),
	 ('Blonde des pÃ¨res Abbaye dAulne','Brouwerij de Smedt','overige','hoge met nof',0.075,4.45),
	 ('Blonde des pÃ¨res Abbaye de Brogne','Brouwerij de Smedt','overige','hoge met nof',0.075,2.61),
	 ('Blonde du menhir','Brasserie LefÃ¨bvre','saison','hoge met nof',0.055,3.7);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Bocholter Kwik Pils','Brouwerij Martens','pilsener','lage',0.05,2.68),
	 ('Bock pils','Brouwerij Palm','pilsener','lage',0.053,3.29),
	 ('Bockhauser pils','Brouwerij Haacht','pilsener','lage',0.05,3.41),
	 ('Bockor','Brouwerij Bockor','pilsener','lage',0.052,2.18),
	 ('Bockor export','Brouwerij Bockor','pilsener','lage',0.052,4.67),
	 ('Bockor pils','Brouwerij Bockor','pilsener','lage',0.052,2.83),
	 ('Bokkereyer','Brouwerij St. Jozef','overige','lage',0.06,4.14),
	 ('Bokrijk tarwe beer','Brouwerij de Block','witbier','hoge met nof',0.05,4.19),
	 ('Bokrijks kruikenbier','Brouwerij Sterkens','tripel','hoge met nof',0.072,3.55),
	 ('Bolderbergs kluizenaarsbier','Brouwerij Sterkens','ale','hoge',0.065,3.18);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Bornem dubbel','Brouwerij Bios','dubbel','hoge met nof',0.08,3.24),
	 ('Bornem St. Bernard','Brouwerij Bios','dubbel','hoge met nof',0.08,4.64),
	 ('Boskeun','De Dolle Brouwers','overige','hoge met nof',0.08,2.5),
	 ('Bourgogne des Flandres','Brouwerij Verhaeghe','Vlaamse bruine','hoge',0.058,2.59),
	 ('Boxer pils','Brouwerij Roman','pilsener','lage',0.051,3.46),
	 ('Brabants witbier','Brouwerij Palm','witbier','hoge met nof',0.05,4.51),
	 ('Brave broeder','Brasserie de Silly','saison','hoge',0.058,4.16),
	 ('Brigand','Brouwerij Van Honsebrouck','tripel','hoge met nof',0.09,2.29),
	 ('Brouwers abdijbier','Brouwerij de Smedt','dubbel','hoge met nof',0.065,2.95),
	 ('Brouwers Bier Belgisch Bier','Brouwerij Piedboeuf','pilsener','lage',0.048,2.88);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Brouwmeester','Alken-Maes (zetel Alken)','pilsener','lage',0.048,3.54),
	 ('Brug ale','Brasserie de Silly','Belgische ale','hoge',0.052,4.08),
	 ('Brugse straffe Hendrik','Huisbrouwerij Straffe Hendrik (groep Riv','overige','hoge met nof',0.054,4.75),
	 ('Bruinekuif','Brouwerij Verhaeghe','Vlaamse bruine','hoge',0.058,3.54),
	 ('Brunehaut 8','Brasserie Allard et Groetembril','overige','hoge+melkzure',0.095,4.46),
	 ('Brunehaut 8 vieille rÃ©serve','Brasserie Allard et Groetembril','overige','hoge+melkzure',0.095,3.65),
	 ('Buffalo','Brouwerij van den Bossche','overige','hoge',0.051,2.87),
	 ('Bush beer','Brasserie Dubuisson','gerstewijn','hoge',0.12,4.42),
	 ('Caeyman pils','Brouwerij van Roy','pilsener','lage',0.05,2.5),
	 ('Cambrinus','Brouwerij Verhaeghe','Belgische ale','hoge',0.056,3.22);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Campbells christmas','Martinas (groep Interbrew)','scotch ale','hoge',0.082,3.6),
	 ('Campbells scotch','Martinas (groep Interbrew)','scotch ale','hoge',0.076,3.33),
	 ('Campus','Brouwerij Bios','overige','hoge met nof',0.08,3.84),
	 ('Cantillon druivenlambic','Brouwerij Cantillon','overige','spontane',0.049,4.24),
	 ('Cantillon framboise','Brouwerij Cantillon','framboise','spontane',0.054,4.66),
	 ('Cantillon Grand Cru','Brouwerij Cantillon','lambic','spontane',0.054,2.59),
	 ('Cantillon kriek','Brouwerij Cantillon','kriekenbier','spontane',0.054,2.95),
	 ('Cara pils','Brouwerij Haacht','pilsener','lage',0.05,2.01),
	 ('Cara pils','Brouwerij van Roy','pilsener','lage',0.05,2.17),
	 ('Cara pils','Brouwerij Martens','pilsener','lage',0.05,2.85);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Cardor','Brouwerij Riva','overige','hoge',0.08,2.71),
	 ('Carillon','Brasserie Ã  Vapeur','overige','hoge met nof',0.08,3.02),
	 ('Catchpole blonde','Brasserie du Bocq','overige','hoge met nof',0.074,4.98),
	 ('Catchpole brune','Brasserie du Bocq','dubbel','hoge met nof',0.088,4.85),
	 ('Caves','Brouwerij Verhaeghe','overige','hoge',0.051,4.28),
	 ('Caves Bruegel gueuze lambic','Brabrux (Groep Belle-Vue)','gueuze','spontane',0.052,4.84),
	 ('Caves Bruegel kriek lambic','Brabrux (Groep Belle-Vue)','kriekenbier','spontane',0.052,3.38),
	 ('Cervesia','Brasserie Dupont','overige','hoge met nof',0.085,3.38),
	 ('Cervoise de lAvouerie dAnthisnes','Brasserie de Silly','Belgische ale','hoge',0.052,4.76),
	 ('Cervoise du Maca','Brasserie LefÃ¨bvre','overige','hoge met nof',0.07,2.67);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Charles Quint','Brouwerij Haacht','dubbel','hoge',0.065,3.06),
	 ('Christmas','Brouwerij Leroy','dubbel','hoge',0.08,2.3),
	 ('Christmas beer (Delhaize)','Brasserie du Bocq','scotch ale','hoge met nof',0.09,3.33),
	 ('Christmas Primus pils','Brouwerij Haacht','pilsener','lage',0.05,4.73),
	 ('Class pils','Brouwerij van Roy','pilsener','lage',0.05,2.68),
	 ('Contra pils','Brouwerij Contreras','pilsener','lage',0.048,3.21),
	 ('Coq hardi pils','Brouwerij Haacht','pilsener','lage',0.05,2.99),
	 ('Corsendonk Agnus','Brasserie du Bocq','tripel','hoge met nof',0.081,3.34),
	 ('Corsendonk Agnus 75 cl.','Brouwerij Bios','overige','hoge met nof',0.08,2.73),
	 ('Corsendonk Agnus van het vat','Brouwerij de Smedt','overige','hoge',0.065,4.63);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Corsendonk Pater','Brouwerij Bios','dubbel','hoge met nof',0.08,3.97),
	 ('CoyHeimsen','Brouwerij van Eecke','dubbel','hoge met nof',0.065,3.97),
	 ('Cristal Alken','Alken-Maes (zetel Alken)','pilsener','lage',0.048,2.92),
	 ('Cristmas van Roy','Brouwerij van Roy','bokbier','hoge',0.073,3.68),
	 ('Crom pils','Brouwerij CrombÃ©','pilsener','lage',0.05,4.67),
	 ('Cupido','Brouwerij Bosteels','overige','hoge',0.048,4.3),
	 ('CuvÃ©e BosquÃ©tia','Brasserie du Bocq','dubbel','hoge met nof',0.067,2.47),
	 ('CuvÃ©e Cervesia Tornacum','Brasserie Allard et Groetembril','overige','hoge+melkzure',0.095,3.47),
	 ('CuvÃ©e de Blatteux','Brouwerij Verhaeghe','Belgische ale','hoge',0.056,4.94),
	 ('CuvÃ©e de Borq - la St. Hubert','Brasserie Maire','overige','hoge',0.05,3.3);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('CuvÃ©e de Briqville','Brouwerij Bios','overige','hoge met nof',0.08,2.65),
	 ('CuvÃ©e de Ciney blonde','St. Guibert (groep Interbrew)','overige','hoge',0.066,4.36),
	 ('CuvÃ©e de Ciney brune','St. Guibert (groep Interbrew)','dubbel','hoge',0.0634,2.87),
	 ('CuvÃ©e de Ciney spÃ©ciale','St. Guibert (groep Interbrew)','overige','hoge',0.085,2.27),
	 ('CuvÃ©e de Huy','Brouwerij Bios','gerstewijn','hoge met nof',0.11,3.74),
	 ('CuvÃ©e de lAscension','Brasserie de lAbbaye des Rocs (Brasseri','overige','hoge met nof',0.09,3.91),
	 ('CuvÃ©e de lErmitage','Union (groep Alken-Maes)','dubbel','hoge',0.07,3.29),
	 ('CuvÃ©e de lErmitage christmas','Union (groep Alken-Maes)','dubbel','hoge',0.07,2.74),
	 ('CuvÃ©e de lEscapade','Brouwerij Bios','gerstewijn','hoge met nof',0.11,4.83),
	 ('CuvÃ©e de la Pucelette','Brasserie LefÃ¨bvre','overige','hoge met nof',0.07,4.95);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('CuvÃ©e de la Thyria','Brasserie du Bocq','dubbel','hoge met nof',0.074,2.24),
	 ('CuvÃ©e de Namur blonde','Brasserie du Bocq','?','?',0.0,3.34),
	 ('CuvÃ©e de Namur blonde','Brouwerij L. Huyghe N.V.','overige','hoge met nof',0.075,4.97),
	 ('CuvÃ©e de St. Gilles blonde','Brouwerij Facon','overige','hoge',0.075,3.85),
	 ('CuvÃ©e de St. Gilles brune','Brouwerij Facon','overige','hoge',0.075,2.32),
	 ('CuvÃ©e des Blatteux','Brouwerij Verhaeghe','Belgische ale','hoge',0.056,4.06),
	 ('CuvÃ©e des Forges','Brasserie LefÃ¨bvre','overige','hoge met nof',0.0,2.33),
	 ('CuvÃ©e des Hauts VouÃ©s','Brasserie de Silly','dubbel','hoge',0.08,3.46),
	 ('CuvÃ©e des moissons blonde','Brasserie Ã  Vapeur','overige','hoge met nof',0.08,2.31),
	 ('CuvÃ©e des moissons rousse','Brasserie Ã  Vapeur','overige','hoge met nof',0.08,2.17);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('CuvÃ©e du Brochon','Brasserie de lAbbaye des Rocs (Brasseri','overige','hoge',0.068,4.91),
	 ('CuvÃ©e du Ptit Lu','Brasserie du Bocq','saison','hoge met nof',0.061,4.05),
	 ('CuvÃ©e du Tchop','Brasserie de Silly','dubbel','hoge',0.08,3.52),
	 ('CuvÃ©e Gerpinoise','Brasserie de Silly','dubbel','hoge',0.08,3.47),
	 ('CuvÃ©e Li Crochon','Brasserie du Bocq','dubbel','hoge met nof',0.088,4.77),
	 ('CuvÃ©e Piconrue','Brasserie dAchouffe','overige','hoge met nof',0.08,2.45),
	 ('CuvÃ©e spÃ©ciale de ChÃ¨vremont','Brasserie du Bocq','overige','hoge met nof',0.074,4.96),
	 ('CuvÃ©e St. Antoine','Brasserie du Bocq','dubbel','hoge met nof',0.088,3.42),
	 ('CuvÃ©e St. Berthuin','Brasserie LefÃ¨bvre','overige','hoge met nof',0.07,3.22),
	 ('CuvÃ©e St.Amand','Bavik - De Brabandere','tripel','hoge',0.075,3.85);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Da Vinci','Brasserie de Silly','dubbel','hoge',0.08,4.58),
	 ('Daiselnaere','Brouwerij De Gouden Boom','dubbel','hoge met nof',0.065,3.37),
	 ('De Brouwers van de Dijle','Lamot (groep Interbrew)','pilsener','lage',0.0525,4.11),
	 ('De Koninck','Brouwerij De Koninck','Belgische ale','hoge',0.05,2.43),
	 ('De Koninck gueuze','Gueuzestekerij De Koninck','gueuze','spontane nof',0.05,3.82),
	 ('De Koninck kriek','Gueuzestekerij De Koninck','kriekenbier','spontane',0.052,3.8),
	 ('De Neve frambozen','De Neve (groep Belle-Vue)','framboise','spontane',0.052,2.56),
	 ('De Neve gueuze gefilterd','De Neve (groep Belle-Vue)','gueuze','spontane',0.052,2.39),
	 ('De Neve gueuze met hergisting','De Neve (groep Belle-Vue)','gueuze','spontane nof',0.052,2.25),
	 ('De Neve kriek lambic','De Neve (groep Belle-Vue)','kriekenbier','spontane',0.052,2.1);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('De Pompeschitter','Brouwerij Leroy','overige','hoge',0.07,4.74),
	 ('De Ryck christmas pale ale','Brouwerij de Ryck','ale','hoge',0.054,3.4),
	 ('De Troch banane-lambic','Brouwerij de Troch','overige','spontane',0.05,3.77),
	 ('De Troch framboise','Brouwerij de Troch','overige','spontane',0.03,3.65),
	 ('De Troch gueuze','Brouwerij de Troch','gueuze','spontane nof',0.05,4.94),
	 ('De Troch kriek','Brouwerij de Troch','kriekenbier','spontane nof',0.055,2.74),
	 ('De Troch mirabelle','Brouwerij de Troch','overige','spontane',0.03,2.88),
	 ('De Troch pÃªche','Brouwerij de Troch','overige','spontane',0.03,4.17),
	 ('De Verboden Vrucht','Brouwerij De Kluis (groep Interbrew)','overige','?',0.0,4.24),
	 ('Deca pils','Brouwerij Isebaert','pilsener','lage',0.048,3.68);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Deconinck pils','Brouwerij Riva','pilsener','lage',0.05,3.68),
	 ('Den Bleeken Moriaan','Brouwerij van Eecke','overige','hoge met nof',0.1,2.37),
	 ('Den Bruynen Moriaen','Brouwerij van Eecke','overige','hoge met nof',0.09,4.78),
	 ('Dentergems witbier - Riva blanche','Brouwerij Riva','witbier','hoge met nof',0.05,2.82),
	 ('Derby pils','Brouwerij Haacht','pilsener','lage',0.05,3.74),
	 ('Dikke','Brouwerij de Smet','overige','lage',0.074,2.24),
	 ('Dikke Mathile','Brouwerij Strubbe','ale','hoge',0.06,3.99),
	 ('Dilirium tremens','Brouwerij L. Huyghe N.V.','overige','hoge met nof',0.095,2.25),
	 ('Dobbel Palm','Brouwerij Palm','Belgische ale','hoge',0.055,3.25),
	 ('Dobbelen bruinen','Brouwerij Roman','Vlaamse bruine','hoge met nof',0.08,4.51);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Dobbelken','Brouwerij Strubbe','Vlaamse bruine','hoge+melkzure',0.05,4.8),
	 ('Domein donker','Brouwerij Bios','dubbel','hoge met nof',0.08,2.47),
	 ('Domein licht','Brouwerij Bios','overige','hoge met nof',0.08,4.95),
	 ('Domus','Huisbrouwerij Domus','overige','lage',0.04,3.34),
	 ('DorÃ©e','Brasserie LefÃ¨bvre','saison','hoge met nof',0.055,2.85),
	 ('Dorp pils','Brouwerij van Roy','pilsener','lage',0.05,2.24),
	 ('Double abbaye de flandres','Brouwerij Riva','dubbel','hoge',0.062,3.64),
	 ('Double Enghien SpÃ©ciale','Brasserie de Silly','dubbel','hoge',0.08,3.49),
	 ('Double spÃ©ciale biÃ¨re dabbaye Enghien','Brasserie de Silly','dubbel','hoge',0.08,4.5),
	 ('Doublette dEnghien','Brasserie de Silly','saison','hoge',0.058,4.06);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Drie Fonteinen framboos','Gueuzestekerij Drie Fonteinen','framboise','spontane',0.06,4.8),
	 ('Drie Fonteinen gueuze','Gueuzestekerij Drie Fonteinen','gueuze','spontane+nof',0.055,3.83),
	 ('Drongens plezierke','Brouwerij Slagmuylder','dubbel','hoge met nof',0.078,2.72),
	 ('Dubbel Domus honingbier','Huisbrouwerij Domus','overige','lage',0.06,3.14),
	 ('Duivels bier','Brouwerij Vander Linden','overige','spontane+hoge',0.055,2.52),
	 ('Duvel pils','Brouwerij Moortgat','pilsener','lage',0.051,4.17),
	 ('E noedn pannenoare','Brasserie Dupont','overige','hoge met nof',0.085,2.32),
	 ('E.S.P. extra strong pils','Brouwerij van Roy','pilsener','lage',0.05,3.08),
	 ('Echte kriek','Brouwerij Verhaeghe','kriekenbier','hoge',0.058,3.43),
	 ('Eksaardse Blauwbuik','Brouwerij Bios','overige','hoge met nof',0.08,2.92);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('El Vert Doudou','Brasserie Ã  Vapeur','overige','hoge met nof',0.08,2.3),
	 ('Elckerlyc','Brouwerij Callewaert','pale ale','hoge',0.065,3.74),
	 ('Engeltjesbier','Brouwerij t Steedje','overige','hoge met nof',0.1,3.8),
	 ('Eupener export','Eupener Bierbrauerei','pilsener','lage',0.043,2.8),
	 ('Eupener kapuziner klosterbier','Eupener Bierbrauerei','overige','lage',0.05,3.59),
	 ('Eupener pils','Eupener Bierbrauerei','pilsener','lage',0.046,4.54),
	 ('Ever natuurbier','Brouwerij Neyt','pilsener','lage',0.055,3.95),
	 ('Extra pilsener','Brouwerij Moortgat','pilsener','lage',0.5,4.11),
	 ('Extra stout','Brouwerij Callewaert','stout','lage',0.05,3.7),
	 ('Extra stout','Brasserie LefÃ¨bvre','stout','hoge',0.065,4.17);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Ezel','Brouwerij Verhaeghe','overige','hoge',0.06,4.74),
	 ('Facon export','Brouwerij Facon','pilsener','lage',0.04,3.19),
	 ('Facon extra stout','Brouwerij Facon','stout','hoge',0.075,2.73),
	 ('Facon ouden bruin','Brouwerij Facon','Vlaamse bruine','hoge+melkzure',0.049,2.1),
	 ('Facon pils','Brouwerij Facon','pilsener','lage',0.049,3.31),
	 ('Facon scotch-christmas','Brouwerij Facon','scotch ale','hoge',0.075,2.25),
	 ('Fakir','Brasserie la Binchoise','overige','hoge met nof',0.062,2.31),
	 ('Fana Blonde','Brasserie du Bocq','tripel','hoge met nof',0.081,2.79),
	 ('Fana brune','Brasserie du Bocq','dubbel','hoge met nof',0.074,2.02),
	 ('Fancy','Bavik - De Brabandere','stout','lage',0.049,2.73);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('FantÃ´me','Brasserie FantÃ´me','overige','hoge met nof',0.08,2.62),
	 ('Faro extra','Brouwerij van Roy','faro','spontane',0.049,2.87),
	 ('Faro Lambic Lindemans','Brouwerij Lindemans','faro','spontane',0.042,4.51),
	 ('Faro Pertotale','Brouwerij Frank Boon N.V.','faro','spontane+hoge',0.06,2.94),
	 ('Faro Vieux Foudre','Brouwerij Vander Linden','faro','spontane',0.055,2.18),
	 ('Fausse Qau','Brasserie du Bocq','overige','hoge met nof',0.074,3.06),
	 ('Felix kriek oud bruin','Brouwerij Clarysse','kriekenbier','hoge',0.055,3.78),
	 ('Felix kriekbier','Brouwerij Clarysse','kriekenbier','hoge',0.055,4.72),
	 ('Felix Oudenaards kriekbier','Brouwerij Clarysse','kriekenbier','hoge',0.06,4.25),
	 ('Felix Oudenaards oud bruin','Brouwerij Clarysse','Vlaamse bruine','hoge',0.055,2.1);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Felix speciaal Oudenaards','Brouwerij Clarysse','Vlaamse bruine','hoge',0.048,4.74),
	 ('Flandrien','Brouwerij Louwaege','Belgische ale','hoge',0.05,3.39),
	 ('Floreffe blond 7','Brasserie LefÃ¨bvre','overige','hoge met nof',0.07,3.74),
	 ('Floreffe double','Brasserie LefÃ¨bvre','dubbel','hoge met nof',0.07,3.52),
	 ('Floreffe la Meilleure','Brasserie LefÃ¨bvre','overige','hoge met nof',0.09,4.37),
	 ('Floreffe triple','Brasserie LefÃ¨bvre','overige','hoge met nof',0.0,3.32),
	 ('Fortuyn','Brasserie de Silly','saison','hoge',0.058,4.47),
	 ('Foudroyante pÃªche','Brouwerij Lindemans','perzikbier','spontane',0.036,4.4),
	 ('Framboise Boon','Brouwerij Frank Boon N.V.','framboise','spontane nof',0.062,3.59),
	 ('Frambozenbier','Brouwerij Vander Linden','framboise','hoge met nof',0.07,2.74);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Freutche','Brasserie LefÃ¨bvre','saison','hoge',0.05,3.95),
	 ('Frissing christmas','Brouwerij van Roy','bokbier','hoge',0.073,3.54),
	 ('Frissing pils','Brouwerij van Roy','pilsener','lage',0.05,3.81),
	 ('Gala pils','Brouwerij Haacht','pilsener','lage',0.05,3.47),
	 ('Gapersbier','Brouwerij Verhaeghe','overige','hoge',0.06,3.9),
	 ('GÃ©ant Altas 8','Brasserie Allard et Groetembril','overige','hoge+melkzure',0.095,4.09),
	 ('GÃ©ant Atlas 9','Brasserie Allard et Groetembril','gerstewijn','hoge met nof',0.105,3.75),
	 ('Gildenbier','Brouwerij Haacht','overige','hoge',0.068,4.49),
	 ('Ginder ale','Martinas (groep Interbrew)','Belgische ale','hoge',0.051,3.18),
	 ('Girardin gueuze 1882','Brouwerij Girardin','gueuze','spontane',0.05,3.46);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Girardin kriek 1882','Brouwerij Girardin','kriekenbier','spontane',0.052,2.75),
	 ('Gluck pils','Brouwerij van Roy','pilsener','lage',0.05,4.36),
	 ('Godefroy','Brouwerij Moortgat','overige','hoge met nof',0.056,2.55),
	 ('Gold pils','Brouwerij van Roy','pilsener','lage',0.05,3.68),
	 ('Golden Girl pils','Brouwerij Isebaert','pilsener','lage',0.048,2.74),
	 ('Golden hop pils','Bavik - De Brabandere','?','?',0.0,3.68),
	 ('Golden Kenia','Brouwerij L. Huyghe N.V.','pilsener','lage',0.051,2.18),
	 ('Golding Campina','Brouwerij Campina','pilsener','lage',0.05,3.86),
	 ('Gouden Carolus','Brouwerij Het Anker','overige','hoge met nof',0.07,4.76),
	 ('Grimbergen dubbel','Union (groep Alken-Maes)','dubbel','hoge',0.06,4.2);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Grimbergen optimo bruno','Union (groep Alken-Maes)','gerstewijn','hoge',0.1,4.72),
	 ('Grimbergen tripel','Union (groep Alken-Maes)','tripel','hoge',0.08,3),
	 ('Grisette biÃ¨re du cayoteu','Brasserie de Silly','Belgische ale','hoge',0.052,4.84),
	 ('Gueuze F.Boon','Brouwerij Frank Boon N.V.','gueuze','spontane nof',0.06,4.21),
	 ('Gueuze F.Boon \"Mariage parfait\"','Brouwerij Frank Boon N.V.','gueuze','spontane nof',0.06,4.5),
	 ('Gueuze framboisÃ©e des Ardennes','Brouwerij De Keersmaeker (groep Alken-Ma','framboise','spontane',0.04,4.91),
	 ('Gueuze lambic Eylenbosch','Brouwerij Eyelenbosch (groep Alken-Maes)','gueuze','spontane',0.05,3.03),
	 ('Gueuze Oud Beersel','Vandervelden','gueuze','spontane',0.06,4.42),
	 ('Gueuze Vieux Foudre','Brouwerij Vander Linden','gueuze','spontane nof',0.055,2.03),
	 ('Gulden Draak','Brouwerij Bios','gerstewijn','hoge met nof',0.11,3.87);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Haacht export','Brouwerij Haacht','pilsener','lage',0.05,2.25),
	 ('Haecht tarwebier','Brouwerij Haacht','witbier','hoge met nof',0.05,3.64),
	 ('Hanssens gueuze','Gueuzestekerij Hanssens','gueuze','spontane',0.055,3.47),
	 ('Hanssens kriek','Gueuzestekerij Hanssens','kriekenbier','spontane',0.06,4.43),
	 ('Hapkin','Brouwerij Louwaege','overige','hoge met nof',0.085,3.73),
	 ('Hellestraatse bruine','Brouwerij de Smedt','Belgische ale','hoge',0.05,3.38),
	 ('Herbakkersbier','Brouwerij de Block','overige','hoge',0.064,3.7),
	 ('Hercule Poirot','Brasserie Allard et Groetembril','gerstewijn','hoge met nof',0.105,3.36),
	 ('Hert ale','Brouwerij De Keersmaeker (groep Alken-Ma','Belgische ale','hoge',0.05,3.72),
	 ('Hertog Jan Pilsener','Artois (groep Interbrew)','pilsener','lage',0.051,3.49);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Het Kapittel abt','Brouwerij van Eecke','overige','hoge met nof',0.1,4.28),
	 ('Het Kapittel dubbel','Brouwerij van Eecke','dubbel','hoge met nof',0.075,2.95),
	 ('Het Kapittel pater','Brouwerij van Eecke','dubbel','hoge met nof',0.065,2.92),
	 ('Het Kapittel prior','Brouwerij van Eecke','overige','hoge met nof',0.09,3.72),
	 ('Hoegaarden grand cru','Brouwerij De Kluis (groep Interbrew)','tripel','hoge met nof',0.087,4.87),
	 ('Holtland lager bier','Brouwerij Haacht','pilsener','lage',0.05,2.18),
	 ('Horse ale','Lamot (groep Interbrew)','Belgische ale','hoge',0.049,3.27),
	 ('Hotteuse grand cru','Brouwerij Roman','tripel','hoge met nof',0.071,4.84),
	 ('Houten kop','Brouwerij Strubbe','overige','hoge met nof',0.065,3.39),
	 ('Huyghe export','Brouwerij L. Huyghe N.V.','pilsener','lage',0.045,3.41);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Ichtegems oud bruin','Brouwerij Strubbe','Vlaamse bruine','hoge+melkzure',0.05,4.88),
	 ('Iguanodon','Brasserie la Binchoise','overige','hoge met nof',0.062,3.17),
	 ('Interpils','Brouwerij Riva','pilsener','lage',0.05,2.21),
	 ('Jack-Op','Brabrux (Groep Belle-Vue)','overige','hoge+spontane',0.05,2.54),
	 ('Jacobins frambozen','Brouwerij Bockor','framboise','hoge+melkzure',0.057,4.09),
	 ('Jacobins gueuze lambic','Brouwerij Bockor','gueuze','hoge+melkzure',0.057,4.83),
	 ('Jacobins kriek lambic','Brouwerij Bockor','kriekenbier','hoge+melkzure',0.057,3.87),
	 ('Jan Buuc','Brouwerij Leroy','overige','hoge',0.07,2.85),
	 ('Jean de Nivilles','Brasserie du Bocq','dubbel','hoge met nof',0.074,3.64),
	 ('Jeunesse de St-Remy','Brouwerij Bios','tripel','hoge met nof',0.09,4.67);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Jobarde','Brasserie Ã  Vapeur','overige','hoge met nof',0.08,4.43),
	 ('Jot-pils','Brouwerij Riva','pilsener','lage',0.05,3.14),
	 ('Judas','Brouwerij van Zulte','overige','hoge met nof',0.085,3.42),
	 ('Julius','Brouwerij De Kluis (groep Interbrew)','overige','hoge met nof',0.87,2.67),
	 ('Jupiler','Kruger (groep Interbrew)','pilsener','lage',0.048,4.09),
	 ('KanterbrÃ¤u','Alken-Maes (zetel Alken)','pilsener','lage',0.048,4.42),
	 ('Kapucienestraetebier','Brouwerij Verhaeghe','overige','hoge',0.051,4.85),
	 ('Karlsquell','Brouwerij Martens','pilsener','lage',0.05,3),
	 ('Kastaar','Brouwerij de Block','overige','hoge',0.064,4.43),
	 ('Kerelsbier donker','Brouwerij Leroy','overige','hoge',0.07,2.15);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Kerelsbier licht','Brouwerij Leroy','superpils','lage',0.065,4.47),
	 ('Kerstbier','Brouwerij van den Bossche','overige','hoge',0.052,4.88),
	 ('Kluyserbier','Brouwerij Sterkens','ale','hoge',0.065,3.01),
	 ('Kob pilsener','Brouwerij De Keersmaeker (groep Alken-Ma','pilsener','lage',0.05,4.41),
	 ('kriek','Brouwerij van Roy','kriekenbier','spontane',0.048,2.01),
	 ('Kriek F.Boon','Brouwerij Frank Boon N.V.','kriekenbier','spontane nof',0.065,3.82),
	 ('Kriek F.Boon \"mariage parfait\"','Brouwerij Frank Boon N.V.','kriekenbier','spontane nof',0.065,2.09),
	 ('Kriek lambic Eylenbosch','Brouwerij Eyelenbosch (groep Alken-Maes)','kriekenbier','spontane',0.052,2.97),
	 ('Kriek Oud Beersel','Brouwerij Museum Oud Beersel','kriekenbier','spontane',0.07,3.6),
	 ('Kriek Vieux Foudre','Brouwerij Vander Linden','kriekenbier','spontane nof',0.055,4.08);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Kriek-lambic Drie Fonteinen','Gueuzestekerij Drie Fonteinen','kriekenbier','spontane',0.06,4.58),
	 ('Kriekenbier','Brouwerij St. Jozef','kriekenbier','lage',0.046,2.68),
	 ('Kronenbourg','Alken-Maes (zetel Alken)','pilsener','lage',0.048,3.64),
	 ('KrÃ¼ger export beer','Kruger (groep Interbrew)','pilsener','lage',0.047,2.17),
	 ('KrÃ¼ger pils','Kruger (groep Interbrew)','pilsener','lage',0.048,3.91),
	 ('LAnvinoise','Brasserie Ã  Vapeur','overige','hoge met nof',0.08,2.05),
	 ('LArsouye blonde','Brasserie du Bocq','overige','hoge met nof',0.074,2.53),
	 ('LArsouye brune','Brasserie du Bocq','dubbel','hoge met nof',0.074,4.48),
	 ('LEblouissante','Brasserie dAchouffe','overige','hoge met nof',0.08,3.84),
	 ('LEveil Wallon','Brasserie Dupont','overige','hoge met nof',0.085,3.73);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('LGayette','Brasserie du Bocq','dubbel','hoge met nof',0.074,2.15),
	 ('LVapeur en folie','Brasserie Ã  Vapeur','overige','hoge met nof',0.08,3.55),
	 ('LVapeur rousse','Brasserie Ã  Vapeur','overige','hoge met nof',0.08,3.32),
	 ('La Bergeotte','Brasserie du Bocq','saison','hoge met nof',0.061,3.94),
	 ('La Bergeotte','Brasserie du Bocq','saison','hoge met nof',0.061,4.73),
	 ('La biÃ¨re du Grand monarque','Brasserie du Bocq','dubbel','hoge met nof',0.067,3.83),
	 ('La Boum 6','Brasserie Allard et Groetembril','saison','hoge met nof',0.07,2.96),
	 ('La Boum 8','Brasserie Allard et Groetembril','overige','hoge+melkzure',0.095,4.3),
	 ('La Boussutoise - BiÃ©re des fagnes','Brasserie du Bocq','?','?',0.0,4.62),
	 ('La Buxus','Brasserie la Binchoise','overige','hoge met nof',0.083,2.19);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('La Cervoise de St. Gery','Brasserie Dupont','overige','hoge met nof',0.085,4.12),
	 ('La Cervoise des Fracs-Gaulois','Brasserie Dupont','overige','hoge met nof',0.085,3.01),
	 ('La Communiale','Brasserie dAchouffe','overige','hoge met nof',0.08,3.7),
	 ('La Condrusienne','Brasserie LefÃ¨bvre','overige','hoge met nof',0.07,4.45),
	 ('La Crupettoise','Brasserie du Bocq','dubbel','hoge met nof',0.074,3.14),
	 ('La CuvÃ©e des Purleux','Brasserie Dupont','overige','hoge met nof',0.085,3.39),
	 ('La Diva','Brasserie LefÃ¨bvre','overige','hoge met nof',0.0,2.5),
	 ('La Druide','Brasserie Allard et Groetembril','gerstewijn','hoge met nof',0.105,3.32),
	 ('La Druide 10','Brasserie Allard et Groetembril','gerstewijn','hoge met nof',0.105,4.11),
	 ('La Durboyse','Brasserie LefÃ¨bvre','overige','hoge met nof',0.07,2.61);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('La Fleurie de Wanze','Brasserie dAchouffe','overige','hoge met nof',0.08,4.69),
	 ('La Gauloise 8Â°','Brasserie du Bocq','dubbel','hoge met nof',0.088,4.63),
	 ('La Gaumaise','Brasserie Maire','overige','hoge',0.05,4.09),
	 ('La Gaumaise brune','Brasserie Maire','overige','hoge',0.05,4.55),
	 ('La Geldonia','Brasserie du Bocq','dubbel','hoge met nof',0.074,2.47),
	 ('La Glorieuse','Brasserie dAchouffe','overige','hoge met nof',0.08,2.72),
	 ('La Hamaide','Brasserie Voisin','saison','hoge',0.055,4.19),
	 ('La Houlette','Brasserie du Bocq','saison','hoge met nof',0.061,4.8),
	 ('La Joyeuse (blonde)','Brasserie Dupont','overige','hoge met nof',0.085,3.42),
	 ('La Joyeuse (brune)','Brasserie Dupont','overige','hoge met nof',0.085,3.7);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('La Laekenoise','Brasserie du Bocq','overige','hoge met nof',0.074,3.22),
	 ('La LiÃ¨geoise blonde','Brouwerij Riva','overige','hoge',0.08,3.01),
	 ('La LiÃ¨geoise brune','Brouwerij Riva','dubbel','hoge met nof',0.08,3.38),
	 ('La Louvoise','Brasserie du Bocq','overige','hoge met nof',0.074,2.87),
	 ('La MalmÃ©dy blonde','Brasserie dAchouffe','overige','hoge met nof',0.08,2.23),
	 ('La MalmÃ©dy brune','Brasserie dAchouffe','overige','hoge met nof',0.08,3.55),
	 ('La Marquise blonde','Brouwerij Riva','overige','hoge',0.08,3.03),
	 ('La Marquise brune','Brouwerij Riva','tripel','hoge',0.08,2.52),
	 ('La Moinette des SorciÃ¨res de Warquignies','Brasserie Dupont','overige','hoge met nof',0.085,4.51),
	 ('La Moneuse','Brasserie de Blaugies','overige','hoge met nof',0.0,4);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('La Moneuse SpÃ©ciale NoÃ«l','Brasserie de Blaugies','overige','hoge met nof',0.0,4.47),
	 ('La Montagnarde','Brasserie de lAbbaye des Rocs (Brasseri','overige','hoge met nof',0.08,2.34),
	 ('La Naiade - CuvÃ©e du Carnaval Tournai','Brasserie LefÃ¨bvre','overige','hoge met nof',0.0,2.28),
	 ('La Neuvilloise','Brasserie dAchouffe','overige','hoge met nof',0.08,2.37),
	 ('La Petite follie','Brasserie de Silly','overige','hoge met nof',0.062,3.04),
	 ('La Poiluchette blonde','Brouwerij L. Huyghe N.V.','overige','hoge met nof',0.075,3.06),
	 ('La Poiluchette blonde','Brouwerij L. Huyghe N.V.','overige','hoge met nof',0.075,4.18),
	 ('La Poiluchette brune','Brouwerij L. Huyghe N.V.','overige','hoge met nof',0.075,3.74),
	 ('La Poiluchette brune','Brouwerij L. Huyghe N.V.','dubbel','hoge met nof',0.075,4.13),
	 ('La Seigneurie','Brasserie LefÃ¨bvre','overige','hoge met nof',0.07,4.45);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('La Vieille bon secours','Brouwerij Riva','tripel','hoge',0.08,4.86),
	 ('La Vieille Salme','Brasserie dAchouffe','overige','hoge met nof',0.08,2.94),
	 ('La Vieillotte du Hurlevent','Brasserie Dupont','overige','hoge met nof',0.085,4.13),
	 ('Lamoral Degmont','Brouwerij van den Bossche','tripel','hoge met nof',0.08,3.83),
	 ('Lamot export','Lamot (groep Interbrew)','pilsener','lage',0.0525,4.75),
	 ('Lamot pilsor','Lamot (groep Interbrew)','pilsener','lage',0.0525,4.24),
	 ('Le Cougnet','Brasserie dAchouffe','overige','hoge met nof',0.08,4.99),
	 ('Le Roy christmas','Brouwerij Leroy','overige','hoge',0.08,4.2),
	 ('Le VaudrÃ©e','Brouwerij Bios','gerstewijn','hoge met nof',0.11,4.02),
	 ('Leffe biÃ¨re russe','St. Guibert (groep Interbrew)','overige','hoge',0.0,2.51);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Leffe blonde','St. Guibert (groep Interbrew)','overige','hoge',0.066,4.5),
	 ('Leffe brune','St. Guibert (groep Interbrew)','dubbel','hoge',0.0634,3.95),
	 ('Leffe radieuse','St. Guibert (groep Interbrew)','overige','hoge',0.085,4.26),
	 ('Leffe triple','Brasserie du Bocq','tripel','hoge met nof',0.081,4.46),
	 ('Leffe vieille cuvÃ©e 8','St. Guibert (groep Interbrew)','overige','hoge',0.084,4.5),
	 ('Lekkerbek','Brouwerij Riva','pilsener','lage',0.05,4.13),
	 ('Li PirÃªye di Licint 6.5','Brasserie la Binchoise','overige','hoge met nof',0.062,2.17),
	 ('Lichtaartse Kwezel','Brasserie LefÃ¨bvre','overige','hoge met nof',0.07,2.43),
	 ('Liefmans','Brouwerij Liefmans (groep Riva)','Vlaamse bruine','hoge',0.05,3.64),
	 ('Liefmans frambozenbier','Brouwerij Liefmans (groep Riva)','framboise','?',0.0,2.92);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Liefmans Goudenband','Brouwerij Liefmans (groep Riva)','Vlaamse bruine','?',0.0,4.68),
	 ('Liefmans kriekbier','Brouwerij Liefmans (groep Riva)','kriekenbier','hoge',0.071,3.64),
	 ('Liezelse witte','Brouwerij Vieille Villers','witbier','lage',0.053,2.17),
	 ('Lilliput - elisir degli gnomi','Brasserie dAchouffe','overige','hoge met nof',0.08,3.93),
	 ('Lindemans cassis','Brouwerij Lindemans','cassisbier','spontane',0.039,2.15),
	 ('Lindemans framboise','Brouwerij Lindemans','framboise','spontane',0.036,2.94),
	 ('Lindemans gueuze gefilterd','Brouwerij Lindemans','gueuze','spontane',0.05,3.26),
	 ('Lindemans gueuze ongefilterd','Brouwerij Lindemans','gueuze','spontane nof',0.055,2.49),
	 ('Lindemans kriek','Brouwerij Lindemans','kriekenbier','spontane',0.039,3.68),
	 ('Livinus blonde','Brouwerij van Eecke','overige','hoge met nof',0.1,2.92);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Livinus brune','Brouwerij van Eecke','overige','hoge met nof',0.09,4.57),
	 ('Loburg','Artois (groep Interbrew)','superpils','lage',0.058,3.1),
	 ('Loteling (donker)','Brouwerij Vieille Villers','dubbel','hoge',0.063,2.79),
	 ('Loteling licht','Brouwerij Vieille Villers','overige','hoge',0.069,2.63),
	 ('Louwaege export','Brouwerij Louwaege','pilsener','lage',0.045,2.77),
	 ('Louwaege stout','Brouwerij Louwaege','stout','lage',0.045,3.98),
	 ('Louwaeges pils','Brouwerij Louwaege','pilsener','lage',0.05,3.57),
	 ('Lowie Kators','Brasserie dAchouffe','overige','hoge met nof',0.08,3.93),
	 ('Lucifer','Brouwerij Riva','overige','hoge',0.08,3.91),
	 ('Maartsen Tonneke','Brouwerij Contreras','ale','hoge met nof',0.054,2.79);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Madie','Brouwerij van Roy','pilsener','lage',0.05,3.21),
	 ('Maes dubbel special','Alken-Maes (zetel Waarloos)','?','?',0.0,2.69),
	 ('Maes pils','Alken-Maes (zetel Waarloos)','pilsener','lage',0.049,4.8),
	 ('Majutte','Brouwerij Strubbe','ale','hoge',0.06,4.95),
	 ('Manneke pils','Bouwer CrombÃ©','?','hoge',0.06,2.34),
	 ('Maredsous 6 (vat)','Brouwerij Moortgat','dubbel','hoge met nof',0.065,3.84),
	 ('Maredsous 6Â° (fles)','Brouwerij Moortgat','dubbel','hoge met nof',0.065,4.2),
	 ('Maredsous 8 (vat)','Brouwerij Moortgat','?','?',0.0,4.49),
	 ('Maredsous 8Â° (fles)','Brouwerij Moortgat','dubbel','hoge',0.08,4.83),
	 ('Maredsous 9Â°','Brouwerij Moortgat','overige','hoge met nof',0.09,2.66);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Martens pils','Brouwerij Martens','pilsener','lage',0.05,2.85),
	 ('MasterbrÃ¤u','Alken-Maes (zetel Alken)','pilsener','lage',0.048,4.24),
	 ('Mc Ewans christmas','Lamot (groep Interbrew)','overige','hoge',0.085,4.67),
	 ('Mc Ewans scotch ale','Lamot (groep Interbrew)','scotch ale','hoge',0.072,2.64),
	 ('Mechelse bruynen','Brouwerij Het Anker','overige','hoge met nof',0.07,3.17),
	 ('Meister extra lager','Brouwerij van Roy','?','?',0.0,2.96),
	 ('Minty','Brouwerij L. Huyghe N.V.','overige','lage',0.054,3.25),
	 ('Moeder Overste','Brasserie LefÃ¨bvre','overige','hoge met nof',0.08,2.4),
	 ('Moinette (blonde)','Brasserie Dupont','overige','hoge met nof',0.085,3.25),
	 ('Moinette (brune)','Brasserie Dupont','overige','hoge met nof',0.085,4.05);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Moinette Athoise','Brasserie Dupont','overige','hoge met nof',0.085,2.48),
	 ('Monseigneur','Brouwerij Bios','dubbel','hoge met nof',0.08,4.26),
	 ('Monseigneur grand cru','Brouwerij Bios','overige','hoge met nof',0.08,2.85),
	 ('Moortgat extra pilsener (fles)','Brouwerij Moortgat','pilsener','lage',0.051,2.5),
	 ('Moortgat extra pilsener (vat)','Brouwerij Moortgat','pilsener','lage',0.051,4.91),
	 ('Moriau gueuze','Gueuzestekerij Moriau','gueuze','spontane',0.055,3.09),
	 ('Moriau kriek','Gueuzestekerij Moriau','kriekenbier','spontane',0.055,4.69),
	 ('Mort Subite cassis','Brouwerij De Keersmaeker (groep Alken-Ma','cassisbier','spontane',0.04,3.2),
	 ('Mort Subite framboise','Brouwerij De Keersmaeker (groep Alken-Ma','framboise','spontane',0.04,2.92),
	 ('Mort Subite gueuze gefilterd','Brouwerij De Keersmaeker (groep Alken-Ma','gueuze','spontane',0.05,2.98);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Mort Subite gueuze ongefilterd','Brouwerij De Keersmaeker (groep Alken-Ma','gueuze','spontane nof',0.065,4.17),
	 ('Mort Subite kriek','Brouwerij De Keersmaeker (groep Alken-Ma','kriekenbier','spontane',0.045,3.92),
	 ('Munck pils','Brouwerij Haacht','pilsener','lage',0.05,2.07),
	 ('Myns pils','Brasserie de Silly','pilsener','lage',0.049,2.6),
	 ('NapolÃ©on','Brouwerij de Smedt','overige','hoge',0.074,4.78),
	 ('Ne Flierefluiter','Brouwerij de Smedt','overige','hoge met nof',0.065,2.09),
	 ('Neyt export','Brouwerij Neyt','pilsener','lage',0.047,3.11),
	 ('Neyt pils','Brouwerij Neyt','pilsener','lage',0.05,4.31),
	 ('NoÃ«l-christmas-Weihnacht','Brouwerij Verhaeghe','tripel','hoge',0.075,4.19),
	 ('NouNou','Brouwerij Bios','Belgische ale','hoge',0.05,3.01);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Odnar','Brouwerij Liefmans (groep Riva)','Vlaamse bruine','hoge',0.048,3.51),
	 ('Oelens boerke','Brouwerij Leroy','superpils','lage',0.065,3.5),
	 ('Oeral','De Dolle Brouwers','overige','hoge met nof',0.06,4.99),
	 ('Old Musketeer','Brouwerij Leroy','overige','hoge',0.08,3.46),
	 ('Op-ale','Brouwerij de Smedt','Belgische ale','hoge',0.05,3.31),
	 ('Ops-ale','St. Jozef','pilsener','lage',0.055,4.19),
	 ('Oud Hoegaarden','Brouwerij De Kluis (groep Interbrew)','witbier','?',0.0,3.02),
	 ('Oud Kriekenbier','Brouwerij CrombÃ©','kriekenbier','hoge',0.061,3.52),
	 ('Oud Zottegems bier','Brouwerij CrombÃ©','overige','hoge',0.065,3.54),
	 ('Oudenaards wit tarwebier','Brouwerij Clarysse','weizenbier','hoge met nof',0.048,2.15);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Palingbier','Brouwerij van Roy','tripel','hoge',0.078,4.13),
	 ('Pandoer','Brouwerij Verhaeghe','Vlaamse bruine','hoge',0.058,3.19),
	 ('Parel pils','Brouwerij van Roy','pilsener','lage',0.05,4.55),
	 ('Pater Lieven','Brouwerij van den Bossche','Belgische ale','hoge',0.054,2.19),
	 ('Paulus','Brouwerij Leroy','Vlaamse bruine','hoge',0.07,4.3),
	 ('Pauwel Kwak','Brouwerij Bosteels','gerstewijn','hoge',0.085,3.91),
	 ('Pax pils','St. Jozef','pilsener','lage',0.048,4.67),
	 ('Pecheresse','Brouwerij Lindemans','perzikbier','spontane',0.036,3.6),
	 ('Peeterman','Brouwerij De Kluis (groep Interbrew)','witbier','hoge',0.045,2.02),
	 ('Perle dHastiÃ¨re','Brasserie LefÃ¨bvre','overige','hoge met nof',0.0,3.27);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Peter Benoit','Brouwerij Leroy','overige','hoge',0.07,2.31),
	 ('Petrus','Bavik - De Brabandere','Vlaamse bruine','hoge',0.055,2.73),
	 ('Pick-up pils','Brouwerij Walrave','pilsener','lage',0.048,4.73),
	 ('Pils','Brouwerij Callewaert','pilsener','lage',0.05,4.47),
	 ('Pils','Brouwerij Riva','pilsener','lage',0.05,3.14),
	 ('Pils artisanale','Brouwerij Lefebvre','pilsener','lage',0.05,3.28),
	 ('PintCousse','Brasserie du Bocq','dubbel','hoge met nof',0.074,4.98),
	 ('Piraat','Brouwerij Bios','gerstewijn','hoge met nof',0.11,4.05),
	 ('Poje','Brasserie Ã  Vapeur','overige','hoge met nof',0.08,3.34),
	 ('Polderbier','Brouwerij t Steedje','overige','hoge met nof',0.09,2.54);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Pony stout','Bavik - De Brabandere','stout','lage',0.049,3.66),
	 ('Poorter','Brouwerij Sterkens','ale','hoge',0.065,2.69),
	 ('Poperings Hommelbier','Brouwerij van Eecke','overige','hoge met nof',0.075,3.46),
	 ('Postel Abdijbier','Brouwerij de Smedt','dubbel','hoge met nof',0.065,4.24),
	 ('Prik pils','Brouwerij Roman','pilsener','lage',0.051,2.8),
	 ('Primus Haacht pils','Brouwerij Haacht','pilsener','lage',0.05,2.29),
	 ('Prisma pils','Brouwerij Haacht','pilsener','lage',0.05,4.03),
	 ('Privat','Brouwerij Riva','pilsener','lage',0.05,2.3),
	 ('Profi pils','Brouwerij van Roy','pilsener','lage',0.05,3.4),
	 ('Prosit pils','Brouwerij Bosteels','pilsener','lage',0.048,2.12);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Pruver','Brouwerij R. Gielen','overige','hoge met nof',0.052,4.37),
	 ('Punch beer (blond)','Brouwerij Facon','overige','hoge',0.075,4.51),
	 ('Rafexport','Brouwerij Contreras','pilsener','lage',0.048,4.43),
	 ('Redor pils','Brasserie Dupont','pilsener','lage',0.055,3.63),
	 ('Reets brooikensbier','Brasserie LefÃ¨bvre','overige','hoge met nof',0.07,2.87),
	 ('ReinbrÃ¤u','Alken-Maes (zetel Alken)','pilsener','lage',0.048,4.46),
	 ('Reuzen oud bier','Brasserie Dupont','overige','hoge met nof',0.085,2.7),
	 ('RÃ©gal Christmas','Brasserie du Bocq','scotch ale','hoge met nof',0.09,4.09),
	 ('RÃ©serve Marie de Hongrie','Brasserie la Binchoise','overige','hoge met nof',0.083,4.38),
	 ('RÃ©tro oude methode','Brouwerij L. Huyghe N.V.','ale','hoge',0.067,4.61);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('RÃ©tro pils oude methode','Brouwerij L. Huyghe N.V.','pilsener','lage',0.051,4.91),
	 ('Rijsels tripel','Brouwerij Bios','tripel','hoge met nof',0.09,2.71),
	 ('Riva 2000','Brouwerij Riva','superpils','lage',0.061,2.84),
	 ('Riva christmas','Brouwerij Riva','dubbel','hoge',0.08,4.06),
	 ('Riva pils','Brouwerij Riva','pilsener','lage',0.05,3.8),
	 ('Rochefort 6','Abbaye Notre Dame De St.RÃ©my','trappist/dubbel','hoge met nof',0.075,4.8),
	 ('Rochefort 8','Abbaye Notre Dame De St.RÃ©my','trappist/gerstewijn','hoge met nof',0.092,4.6),
	 ('Rochefort 10','Abbaye Notre Dame De St.RÃ©my','trappist/gerstewijn','hoge met nof',0.113,3.6),
	 ('Rochus','Brouwerij de Ryck','overige','hoge',0.062,2.22),
	 ('Rodal','De Neve (groep Belle-Vue)','overige','hoge+spontane',0.05,4.3);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Rodenbach grand cru','Bierbrouwerij Rodenbach','Vlaamse bruine','hoge+melkzure',0.067,3.84),
	 ('Roman export','Brouwerij Roman','pilsener','lage',0.051,4.28),
	 ('Roman Oudenaards','Brouwerij Roman','Vlaamse bruine','hoge',0.05,4.87),
	 ('Romy luxe','Brouwerij Roman','pilsener','lage',0.056,3.54),
	 ('Romy pils','Brouwerij Roman','pilsener','lage',0.051,4.08),
	 ('RosÃ© de Cambrinus','Brouwerij Cantillon','framboise','spontane',0.054,4.76),
	 ('Royal pils','Brouwerij Riva','pilsener','lage',0.05,3.59),
	 ('RUCA pils','Brouwerij Isebaert','pilsener','lage',0.048,4.66),
	 ('Safir pils','Artois (groep Interbrew)','pilsener','lage',0.051,4.53),
	 ('Saison 1900','Brasserie LefÃ¨bvre','saison','hoge',0.05,3.68);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Saison de Pipaux','Brasserie Ã  Vapeur','saison','hoge met nof',0.065,2.81),
	 ('Saison de Silly','Brasserie de Silly','saison','hoge',0.054,4.01),
	 ('Saison Dupont','Brasserie Dupont','saison','hoge met nof',0.065,3.6),
	 ('Saison Regal','Brasserie du Bocq','saison','hoge met nof',0.061,3.96),
	 ('Salvator abdijbier','Brouwerij van Roy','bokbier','hoge',0.073,4.04),
	 ('Samwell pils','Brouwerij van Roy','pilsener','lage',0.05,3.28),
	 ('Sanctus','Brouwerij Moortgat','dubbel','hoge met nof',0.065,2.31),
	 ('Sandersput pils','Brouwerij van Roy','pilsener','lage',0.05,2.7),
	 ('Sas export','Brouwerij Leroy','pilsener','lage',0.05,4.58),
	 ('Sas pils','Brouwerij Leroy','pilsener','lage',0.05,3.77);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('SasbraÃ¼','Brouwerij Leroy','superpils','lage',0.065,3.15),
	 ('Satyre','Brouwerij de Block','dubbel','hoge',0.08,2.41),
	 ('Schavuit','Brouwerij Callewaert','Vlaamse bruine','hoge',0.08,3.6),
	 ('Scotch','Brasserie de Silly','scotch ale','hoge',0.085,2.77),
	 ('Sezoens','Brouwerij Martens','overige','hoge',0.06,4.06),
	 ('Si Boune (blonde)','Brasserie du Bocq','tripel','hoge met nof',0.081,3.98),
	 ('Si Boune (brune)','Brasserie du Bocq','dubbel','hoge met nof',0.074,2.73),
	 ('Silbrau dort','Brasserie de Silly','saison','hoge',0.058,2.73),
	 ('Silver pils','Brouwerij Moortgat','pilsener','lage',0.051,3.43),
	 ('Simon NoÃ«l','Brasserie Simon','bokbier','lage',0.07,3.98);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Simon pils','Brasserie Simon','pilsener','lage',0.048,4.6),
	 ('Simon RÃ©gal','Brasserie Simon','dortmunder','lage',0.055,3.04),
	 ('Sinaaise bok','Brouwerij Bios','overige','hoge met nof',0.08,2.43),
	 ('Ski-rodt biermuseum blonde','Brasserie du Bocq','overige','hoge met nof',0.074,4.03),
	 ('Ski-rodt biermuseum brune','Brasserie du Bocq','dubbel','hoge met nof',0.074,4.86),
	 ('Slag lager','Brouwerij Slagmuylder','dortmunder','lage',0.055,4.2),
	 ('Slaghmuylder kerstbier','Brouwerij Slagmuylder','dortmunder','lage',0.055,4.4),
	 ('Slaghmuylder paasbier','Brouwerij Slagmuylder','dortmunder','lage',0.055,4.43),
	 ('Smash','Brouwerij Riva','tripel','hoge',0.08,3.92),
	 ('Soldaat','Brouwerij Sterkens','dubbel','hoge',0.055,4.33);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Soleilmont double','Brasserie LefÃ¨bvre','overige','hoge met nof',0.07,4.89),
	 ('Soleilmont triple','Brasserie de Silly','scotch ale','hoge',0.085,3.45),
	 ('Sparta pils','Brouwerij Bios','pilsener','lage',0.05,3.59),
	 ('Speciaal Natuurbier','Brouwerij Strubbe','dortmunder','lage',0.045,2.6),
	 ('Special 6','Brouwerij de Block','Belgische ale','hoge',0.047,3.25),
	 ('Special De Ryck','Brouwerij de Ryck','Belgische ale','hoge',0.04,3.43),
	 ('Special Drink center Shape','Brouwerij L. Huyghe N.V.','pilsener','lage',0.051,2.38),
	 ('Special Katje','Brouwerij Leroy','overige','hoge',0.07,2.64),
	 ('Special Roman','Brouwerij Roman','Vlaamse bruine','hoge',0.055,4.07),
	 ('Speciale Aerts','Brouwerij Palm','Belgische ale','hoge',0.048,4.41);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Speciale Palm','Brouwerij Palm','Belgische ale','hoge',0.052,4.84),
	 ('Speciale Stop','Bavik - De Brabandere','Belgische ale','hoge',0.05,2.98),
	 ('SpÃ©ciale de Fourquepire','Brasserie Dupont','overige','hoge met nof',0.085,4.38),
	 ('SpÃ©ciale des GÃ©ants','Brasserie LefÃ¨bvre','overige','hoge met nof',0.0,4.94),
	 ('SpÃ©ciale Villers Saint-Ghislain','Brasserie de Silly','dubbel','hoge',0.08,3.56),
	 ('St. AndrÃ©','Brasserie LefÃ¨bvre','overige','hoge met nof',0.0,3.98),
	 ('St. Benoit blonde','Brasserie du Bocq','overige','hoge met nof',0.074,4.24),
	 ('St. Benoit brune','Brasserie du Bocq','dubbel','hoge met nof',0.074,4.25),
	 ('St. Bernardus','Brouwerij St. Bernardus','dubbel','hoge met nof',0.075,3.52),
	 ('St. Denis dark','Brouwerij Sterkens','ale','hoge',0.065,2.86);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('St. Denise grand cru','Brouwerij Sterkens','tripel','hoge met nof',0.072,4.73),
	 ('St. Feuillien (blonde)','Brasserie Friart','overige','hoge met nof',0.055,4.08),
	 ('St. Feuillien (blonde)','Brasserie du Bocq','overige','hoge met nof',0.055,4.21),
	 ('St. Feuillien (brune)','Brasserie du Bocq','dubbel','hoge met nof',0.074,3.83),
	 ('St. Feuillien (brune)','Brasserie Friart','dubbel','hoge met nof',0.074,4.49),
	 ('St. Feuillien cuvÃ©e de noÃ«l','Brasserie du Bocq','scotch ale','hoge met nof',0.09,2.99),
	 ('St. Hubert','Brasserie de lAbbaye des Rocs (Brasseri','overige','hoge',0.068,2.46),
	 ('St. Laurent','Brouwerij Sterkens','ale','hoge',0.065,4.32),
	 ('St. Laurent triple','Brouwerij Sterkens','tripel','hoge met nof',0.072,3.25),
	 ('St. LÃ©ger','Brasserie LefÃ¨bvre','overige','hoge met nof',0.07,4.28);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('St. Louis cassis kir royal','Brouwerij Van Honsebrouck','overige','spontane',0.05,3.65),
	 ('St. Louis framboisÃ©e','Brouwerij Van Honsebrouck','framboise','spontane',0.05,3.4),
	 ('St. Louis gueuze lambic','Brouwerij Van Honsebrouck','gueuze','spontane',0.05,4.04),
	 ('St. Louis kriek lambic','Brouwerij Van Honsebrouck','kriekenbier','spontane',0.05,2.03),
	 ('St. Louis pÃªche lambic','Brouwerij Van Honsebrouck','overige','spontane',0.05,2),
	 ('St. Mengold 25cl.','Brasserie de Silly','dubbel','hoge',0.08,4.94),
	 ('St. Mengold Huy','Brasserie Ã  Vapeur','overige','hoge met nof',0.08,4.67),
	 ('St. Sebastiaan','Brouwerij Sterkens','ale','hoge',0.065,3.53),
	 ('St. Sixtus Abdij Abt 12','Brouwerij St. Bernardus','gerstewijn','hoge met nof',0.095,4.66),
	 ('St. Sixtus Abdij Pater 6','Brouwerij St. Bernardus','dubbel','hoge met nof',0.06,4.72);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('St. Sixtus Abdij Prior 8','Brouwerij St. Bernardus','dubbel','hoge met nof',0.075,4.59),
	 ('Steedje special','Brouwerij t Steedje','overige','hoge met nof',0.085,3.81),
	 ('Steedje tripel','Brouwerij t Steedje','tripel','hoge met nof',0.08,3.26),
	 ('Steenezel','Brouwerij Bios','gerstewijn','hoge met nof',0.11,2.89),
	 ('Stella Artois','Artois (groep Interbrew)','pilsener','lage',0.051,2.64),
	 ('Stille Nacht','De Dolle Brouwers','gerstewijn','hoge met nof',0.08,2.56),
	 ('Stoere pils','Brouwerij van Roy','pilsener','lage',0.05,2.86),
	 ('Stoeren Bonk','Brouwerij Bios','overige','hoge met nof',0.063,4.62),
	 ('Stout','Brouwerij Strubbe','stout','hoge',0.05,3.52),
	 ('Stout Leroy','Brouwerij Leroy','stout','lage',0.06,4.76);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Stropken','Brouwerij Slagmuylder','overige','hoge met nof',0.06,2.21),
	 ('Strubbe export','Brouwerij Strubbe','pilsener','lage',0.045,3.8),
	 ('Sublim','Brouwerij Piessens','overige','hoge met nof',0.085,4.35),
	 ('Suna pils','Brouwerij Leroy','pilsener','lage',0.05,2.34),
	 ('Super 64','Brasserie de Silly','Belgische ale','hoge',0.052,2.67),
	 ('Super des Fagnes','Brasserie du Bocq','tripel','hoge met nof',0.081,4.32),
	 ('Super Gueuze Cantillon','Brouwerij Cantillon','gueuze','spontane',0.054,2.6),
	 ('Super houblo','Brasserie LefÃ¨bvre','overige','hoge met nof',0.0,4.05),
	 ('Super Lait des Feuilles Mortes','Brasserie Dupont','overige','hoge met nof',0.085,4.44),
	 ('Super pils','Brouwerij Strubbe','pilsener','lage',0.045,2.07);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Supra pils','Artois (groep Interbrew)','pilsener','lage',0.051,4.01),
	 ('Teutenbier','Brouwerij van Roy','overige','hoge met nof',0.075,2.83),
	 ('Thouroutenaere','Brouwerij Louwaege','overige','hoge met nof',0.085,3.13),
	 ('Timmermans cassis lambic','Brouwerij Timmermans N.V.','cassisbier','spontane',0.052,2.18),
	 ('Timmermans framboise lambic','Brouwerij Timmermans N.V.','framboise','spontane',0.052,2.49),
	 ('Timmermans gueuze caveau','Brouwerij Timmermans N.V.','gueuze','spontane nof',0.052,3.9),
	 ('Timmermans gueuze lambic','Brouwerij Timmermans N.V.','gueuze','spontane',0.052,4.05),
	 ('Timmermans kriek lambic','Brouwerij Timmermans N.V.','kriekenbier','spontane',0.052,3.54),
	 ('Timmermans pÃªche lambic','Brouwerij Timmermans N.V.','perzikbier','spontane',0.052,3.57),
	 ('Tongerlo dubbel','St. Guibert (groep Interbrew)','dubbel','hoge',0.0634,2.2);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Tongerlo Norbertijnerbier','St. Guibert (groep Interbrew)','dubbel','hoge',0.0634,4.32),
	 ('Tonneke','Brouwerij Contreras','Belgische ale','hoge',0.05,3.99),
	 ('Tradition des Moines blonde','Brasserie du Bocq','overige','hoge met nof',0.074,2),
	 ('Tradition des Moines brune','Brasserie du Bocq','dubbel','hoge met nof',0.074,2.03),
	 ('Travelling','Brasserie du Bocq','overige','hoge met nof',0.074,2.16),
	 ('Triple','Brouwerij Riva','tripel','hoge',0.076,2.72),
	 ('Triple Abbaye dAulne','Brouwerij de Smedt','tripel','hoge met nof',0.09,2.1),
	 ('Triple Aulne','Brouwerij de Smedt','tripel','hoge met nof',0.075,3.32),
	 ('Triple de Val-Dieu','Brouwerij Van Honsebrouck','tripel','hoge met nof',0.09,2.33),
	 ('Triple Moine','Brasserie du Bocq','tripel','hoge met nof',0.081,2.66);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Triple Petrus','Bavik - De Brabandere','tripel','hoge',0.075,4.34),
	 ('Triple saison Roland','Brasserie LefÃ¨bvre','saison','hoge',0.05,2.73),
	 ('Triple Soleilmont','Brasserie de Silly','dubbel','hoge',0.08,4.61),
	 ('Triple St. Pierre','Brasserie Dupont','overige','hoge met nof',0.085,3.85),
	 ('Triple Toison dor','Brouwerij Het Anker','tripel','hoge met nof',0.07,3.41),
	 ('Triple Villers','Brouwerij Vieille Villers','tripel','hoge',0.065,3.51),
	 ('Trippel Bornem','Brouwerij Bios','tripel','hoge met nof',0.09,2.34),
	 ('Ulricher lager','Brouwerij Girardin','pilsener','lage',0.05,2.15),
	 ('Upper 19','Brouwerij van Roy','tripel','hoge',0.078,4.76),
	 ('V Keute di Nameur blonde','Brasserie LefÃ¨bvre','overige','hoge met nof',0.07,3.32);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Vaartlander','Brouwerij Bios','tripel','hoge met nof',0.09,3.32),
	 ('Val dheure (blonde. 25 cl.)','Brasserie du Bocq','saison','hoge met nof',0.061,4.66),
	 ('Val dheure (blonde. 75 cl.)','Brasserie du Bocq','tripel','hoge met nof',0.081,2.31),
	 ('Val dHeure (brune. 25 cl.)','Brasserie du Bocq','dubbel','hoge met nof',0.074,4.58),
	 ('Val dHeure (brune. 75 cl.)','Brasserie du Bocq','dubbel','hoge met nof',0.088,4.99),
	 ('Val-Dieu triple','Brouwerij Van Honsebrouck','tripel','hoge met nof',0.09,3.2),
	 ('Van der Ghinstes Tripel','Brouwerij Bockor','Vlaamse bruine','hoge+melkzure',0.055,2.03),
	 ('vander Linden lambik','Brouwerij Vander Linden','lambic','spontane',0.055,4.57),
	 ('Vedett','Brouwerij Moortgat','pilsener','lage',0.051,2.74),
	 ('Vera pils','Brouwerij Verhaeghe','pilsener','lage',0.04,4.01);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('VerabraÃ¼ super pils','Brouwerij Verhaeghe','pilsener','lage',0.04,3.8),
	 ('VerabraÃ¼ urtyp','Brouwerij Verhaeghe','pilsener','lage',0.045,4.98),
	 ('Verhaeghe export','Brouwerij Verhaeghe','pilsener','lage',0.04,2.49),
	 ('Vichtenaar','Brouwerij Verhaeghe','Vlaamse bruine','hoge',0.058,4.52),
	 ('Vieille des Estinnes','Brasserie Dupont','overige','hoge met nof',0.075,4.11),
	 ('Vieille Villers','Brouwerij Vieille Villers','dubbel','hoge',0.062,2.01),
	 ('Vieux Bruges gueuze lambic','Brouwerij Van Honsebrouck','gueuze','spontane',0.05,4.73),
	 ('Vieux Bruges framboisÃ©e','Brouwerij Van Honsebrouck','framboise','spontane',0.05,3.61),
	 ('Vieux Bruges gueuze lambic','Brouwerij Van Honsebrouck','gueuze','spontane',0.05,4.88),
	 ('Vieux Bruges kriek lambic','Brouwerij Van Honsebrouck','kriekenbier','spontane',0.05,2.54);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Vieux Temps','St. Guibert (groep Interbrew)','Belgische ale','hoge',0.052,2.08),
	 ('Villers tripel','Brouwerij Vieille Villers','overige','hoge',0.069,3.77),
	 ('Vlaske','Brouwerij de Block','overige','hoge',0.064,4.62),
	 ('Voisin saison','Brasserie Voisin','saison','hoge',0.055,3.8),
	 ('Voisin super','Brasserie Voisin','Belgische ale','hoge',0.052,3.12),
	 ('Vondel','Brouwerij Riva','tripel','hoge',0.08,2.22),
	 ('Walrave export','Brouwerij Walrave','pilsener','lage',0.048,2.72),
	 ('Watneys pale ale','Union (groep Alken-Maes)','pale ale','hoge',0.054,4.93),
	 ('Watneys red','Union (groep Alken-Maes)','ale','hoge',0.056,2.52),
	 ('Watneys scotch','Union (groep Alken-Maes)','scotch ale','hoge',0.077,4.8);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Watous wit bier','Brouwerij van Eecke','weizenbier','hoge met nof',0.05,2.43),
	 ('Wellington red lion','Union (groep Alken-Maes)','ale','hoge',0.056,4.74),
	 ('Wellington scotch ale','Union (groep Alken-Maes)','dubbel','hoge',0.06,2.44),
	 ('West pils','Brouwerij Leroy','pilsener','lage',0.05,4.96),
	 ('Westmalle tripel','Abdij der Trappisten van Westmalle','trappist/dubbel','?',0.0,3.5),
	 ('Westmalle dubbel','Abdij der Trappisten van Westmalle','?','?',0.0,3.61),
	 ('Westmalle extra','Abdij der Trappisten van Westmalle','trappist/tripel','hoge met nof',0.09,2.57),
	 ('Westvleteren extra 8','Abdij St. Sixtus','trappist/gerstewijn','hoge met nof',0.113,3.01),
	 ('Westvleteren abt 12','Abdij St. Sixtus','trappist/dubbel','hoge met nof',0.08,2.32),
	 ('Westvleteren special 6','Abdij St. Sixtus','trappist/dubbel','hoge met nof',0.06,3.59);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Wets gueuze','Gueuzestekerij Wets','gueuze','spontane',0.055,2.99),
	 ('Wets kriek','Gueuzestekerij Wets','kriekenbier','spontane',0.06,2.17),
	 ('Whitbread extra stout','Martinas (groep Interbrew)','stout','hoge',0.053,2.86),
	 ('Whitbread pale ale','Martinas (groep Interbrew)','pale ale','hoge',0.056,2.83),
	 ('Wiels pils','Wielemans','pilsener','lage',0.05,3.55),
	 ('Wiels pils','Artois (groep Interbrew)','pilsener','lage',0.051,4.25),
	 ('Wieze christmas','Brouwerij van Roy','bokbier','hoge',0.073,2.59),
	 ('Wieze pils','Brouwerij van Roy','pilsener','lage',0.05,4.2),
	 ('Wilson mild stout','Brouwerij Bios','stout','lage',0.05,2.25),
	 ('Witkap pater dubbele pater','Brouwerij Slagmuylder','dubbel','hoge met nof',0.074,2.64);
INSERT INTO bier (naam,brouwer,"type",gisting,perc,inkoop_prijs) VALUES
	 ('Witkap pater stimulo','Brouwerij Slagmuylder','overige','hoge met nof',0.062,4.44),
	 ('Witkap pater tripel','Brouwerij Slagmuylder','tripel','hoge met nof',0.076,3.28),
	 ('Witte blonde kuif','Brouwerij Clarysse','weizenbier','hoge met nof',0.048,4.08),
	 ('Wittekop','Brouwerij Riva','witbier','hoge met nof',0.05,2.58),
	 ('Wonderbier','Brouwerij Moortgat','pilsener','lage',0.051,4.65),
	 ('Zafke 25cl.','Brasserie LefÃ¨bvre','overige','hoge met nof',0.07,4.52),
	 ('Zedelgemse Martelaar','Brouwerij Strubbe','ale','hoge',0.06,3.64),
	 ('Zerewever','Brouwerij Verhaeghe','overige','hoge',0.06,2.64),
	 ('Zottegems bruin','Brouwerij CrombÃ©','overige','hoge',0.045,3.29),
	 ('Zulte','Brouwerij van Zulte','Vlaamse bruine','hoge',0.05,3.53);